# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: Set up wallet-plugin-oreid
    command: cd wallet-plugin-oreid && yarn install
  - name: Set up web-ui-renderer-oreid-sample
    command: cd web-ui-renderer-oreid-sample && yarn install
  - name: Link deps
    command: cd wallet-plugin-oreid && yarn link && cd ../web-ui-renderer-oreid-sample && yarn link "wallet-plugin-oreid"
  - name: run web-ui-renderer-oreid-sample templates
    command: cd web-ui-renderer-oreid-sample && yarn run dev
# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
ports:
  - name: Frontend
    description: Port 8000 for the frontend
    port: 8080
    onOpen: open-browser

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
